services:
  load-balancer:
    build:
      context: .
      dockerfile: tickmaster-load-balancer/Dockerfile
    container_name: tickmaster-lb
    ports:
      - "1915:1915"
    networks:
      - tickmaster-net

  server:
    build:
      context: .
      dockerfile: tickmaster-server/Dockerfile
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=tickmaster
      - DB_USER=root
      - DB_PASSWORD=1711
      - INTENTOS=3
      - LB_URL=http://load-balancer:1915
      - SERVICE_NAME=servidor
      - PASARELA_URL=http://pasarela:1916/cobrar
      - CALLBACK_URL=http://server:1914/webhook/pago
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tickmaster-net
    depends_on:
      - load-balancer
      - pasarela

  pasarela:
    build:
      context: .
      dockerfile: tickmaster-pasarela/Dockerfile
    container_name: tickmaster-pasarela
    ports:
      - "1916:1916"
    networks:
      - tickmaster-net

  nginx:
    image: nginx:alpine
    container_name: tickmaster-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./tickmaster-frontend:/usr/share/nginx/html:ro
    networks:
      - tickmaster-net
    depends_on:
      - server

networks:
  tickmaster-net:
    driver: bridge
