# Las rutas de nuestros servidores principales se registran dinámicamente vía API.
#
# SI TIENES OTRO BACKEND que NO se registra automáticamente, usa las siguientes reglas:
# 
# 1. Si el backend corre en tu computadora (PowerShell/CMD) y el Balanceador está en Docker:
# otroservicio=http://host.docker.internal:5000
#
# 2. Si el backend corre en OTRO contenedor Docker:
# usuarios=http://nombre-del-contenedor:8080
#
# Evita usar "localhost" aquí si corres en Docker, ya que "localhost" significa 
# "el interior del contenedor del Balanceador", por lo que te dará Connection Refused.
#
#servidor=http://localhost:1914
